fix: indexing workaround now works in more cases
* `hasIndexingBug`: use the build number from `ApplicationInfo` instead of
  `BuildNumber.currentVersion()` because it is always present and it is more
  likely to contain the true platform version.

* `forceIndexing`: instead of relying on the build number (even though it is
  likely to be more correct now), just try the 2024.1 approach and fall back to
  the 2023.2 one on NoClassDefFoundError.